project:
  type: website
  output-dir: docs

website:
  title: "Finn's Awesome CSCI 0451 Blog!!!"
  navbar:
    background: "#112a39"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Norvoke/norvoke.github.io
      - icon: twitter
        href: https://twitter.com

format:
  html:
    title-block-banner: img/snow.jpg
    title-block-banner-color: black
    theme: minty
    fontcolor: "#2F4F4F"
    css: styles.css





